targets:
  $default:
    builders:
      drift_dev:
        options:
          schema_dir: lib/core/database/drift_schemas/
          databases:
            # Required: A name for the database and it's path
            my_database: lib/core/database/database.dart
